---
pool: dotnet6

trigger:
  - master

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
                command: build
                projects: '*.csproj'